/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!


goog.provide('proto.protocol.PushServiceConfigMsg');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.protocol.PushServiceConfigMsg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.protocol.PushServiceConfigMsg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.protocol.PushServiceConfigMsg.displayName = 'proto.protocol.PushServiceConfigMsg';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.protocol.PushServiceConfigMsg.prototype.toObject = function(opt_includeInstance) {
  return proto.protocol.PushServiceConfigMsg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.protocol.PushServiceConfigMsg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protocol.PushServiceConfigMsg.toObject = function(includeInstance, msg) {
  var f, obj = {
    fetchbucket: jspb.Message.getField(msg, 1),
    usebucketv2: jspb.Message.getField(msg, 2),
    clientversion: jspb.Message.getField(msg, 3),
    cloudversion: jspb.Message.getField(msg, 4),
    dots: jspb.Message.getField(msg, 5)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.protocol.PushServiceConfigMsg}
 */
proto.protocol.PushServiceConfigMsg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.protocol.PushServiceConfigMsg;
  return proto.protocol.PushServiceConfigMsg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.protocol.PushServiceConfigMsg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.protocol.PushServiceConfigMsg}
 */
proto.protocol.PushServiceConfigMsg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setFetchbucket(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setUsebucketv2(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setClientversion(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCloudversion(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDots(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.protocol.PushServiceConfigMsg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.protocol.PushServiceConfigMsg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.protocol.PushServiceConfigMsg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protocol.PushServiceConfigMsg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {boolean} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBool(
      1,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBool(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeInt32(
      5,
      f
    );
  }
};


/**
 * optional bool fetchBucket = 1;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.protocol.PushServiceConfigMsg.prototype.getFetchbucket = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.protocol.PushServiceConfigMsg.prototype.setFetchbucket = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.protocol.PushServiceConfigMsg.prototype.clearFetchbucket = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.protocol.PushServiceConfigMsg.prototype.hasFetchbucket = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool useBucketV2 = 2;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.protocol.PushServiceConfigMsg.prototype.getUsebucketv2 = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.protocol.PushServiceConfigMsg.prototype.setUsebucketv2 = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.protocol.PushServiceConfigMsg.prototype.clearUsebucketv2 = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.protocol.PushServiceConfigMsg.prototype.hasUsebucketv2 = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional int32 clientVersion = 3;
 * @return {number}
 */
proto.protocol.PushServiceConfigMsg.prototype.getClientversion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.protocol.PushServiceConfigMsg.prototype.setClientversion = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.protocol.PushServiceConfigMsg.prototype.clearClientversion = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.protocol.PushServiceConfigMsg.prototype.hasClientversion = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional int32 cloudVersion = 4;
 * @return {number}
 */
proto.protocol.PushServiceConfigMsg.prototype.getCloudversion = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.protocol.PushServiceConfigMsg.prototype.setCloudversion = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.protocol.PushServiceConfigMsg.prototype.clearCloudversion = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.protocol.PushServiceConfigMsg.prototype.hasCloudversion = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional int32 dots = 5;
 * @return {number}
 */
proto.protocol.PushServiceConfigMsg.prototype.getDots = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.protocol.PushServiceConfigMsg.prototype.setDots = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.protocol.PushServiceConfigMsg.prototype.clearDots = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.protocol.PushServiceConfigMsg.prototype.hasDots = function() {
  return jspb.Message.getField(this, 5) != null;
};


